- name: check that mandatory variables are correctly defined
  assert:
    quiet: yes
    that: "{{ item }}"
    fail_msg: "One or more variables are not correctly defined. Check role documentation: https://gitlab.com/nodiscc/xsrv/-/tree/master/roles/mumble"
  with_items:
    - readme_gen_netdata_badges | type_debug == "list"

- name: check that variables are correctly defined (readme_gen_netdata_badges)
  assert:
    quiet: yes
    that:
      - item.chart is string
      - item.alarm is string
      - (item.label is not defined) or (item.label is string)
    fail_msg: "One or more variables are not correctly defined. Check role documentation: https://gitlab.com/nodiscc/xsrv/-/tree/master/roles/common"
  with_items: "{{ readme_gen_netdata_badges }}"
