- name: import variable checks tasks
  import_tasks: checks.yml
  tags:
    - monitoring
    - rsyslog
    - checks

- name: import rsyslog configuration tasks
  import_tasks: rsyslog.yml
  become: yes
  tags:
    - monitoring
    - rsyslog

- name: import ansible facts configuration tasks
  import_tasks: fact.yml
  become: yes
  tags:
    - monitoring
    - rsyslog

- name: apply configuration (flush handlers)
  meta: flush_handlers
  tags:
    - monitoring
    - rsyslog
