# Fully Qualified Domain Name for the owncast instance
owncast_fqdn: "owncast.CHANGEME.org"
# the owncast OCI image to pull
owncast_image: "docker.io/owncast/owncast:latest"
# password to access the admin interfaces at /admin (username admin)
owncast_admin_password: "CHANGEME"
# start/stop the gitea service, enable/disable it on boot (yes/no) (redirect users to maintenance page if disabled)
owncast_enable_service: yes
# firewall zones for the owncast RTMP stream ingestion service (zone, state), if nodiscc.xsrv.common/firewalld role is deployed
# 'zone:' is one of firewalld zones, set 'state:' to 'disabled' to remove the rule (the default is state: enabled)
owncast_firewalld_zones:
  - zone: internal
    state: enabled
  - zone: public
    state: enabled
